# cat > /etc/hosts <<EOF
172.31.15.204 sanjay-kube-master
172.31.4.75 sanjay-kube-node1
172.31.8.220 sanjay-kube-node2
127.0.0.1 localhost
EOF


cat > /etc/sysctl.d/k8s.conf <<EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

sudo apt install curl apt-transport-https vim git wget gnupg2 software-properties-common lsb-release ca-certificates uidmap -y

sudo mkdir -p /etc/apt/keyrings


curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg


echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update && sudo apt-get install containerd.io

containerd config default | sudo tee /etc/containerd/config.toml


systemctl daemon-reload
systemctl enable --now containerd
systemctl restart --now containerd
systemctl status containerd --no-pager


sudo sh -c "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"

sudo sh -c "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

kubectl label node sanjay-kube-node1 node-role.kubernetes.io/node=
kubectl label node sanjay-kube-node2 node-role.kubernetes.io/node=




apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stable-perl
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: stable-perl
  template:
    metadata:
      labels:
        tier: stable-perl
    spec:
      containers:
      - name: stable-perl
        image: nginx:1.19
