apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp1
spec:
  replicas: 4
  selector:
    matchLabels:
      team: database
  template:
    metadata:
      labels:
        team: database
    spec:
      containers:
      - name: webapp1
        image: nginx:1.19






