apiVersion: v1
kind: Service
metadata:
  name: cherry
  labels:
    app: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 6379
    NodePort: 30001






